load("@rules_go//go:def.bzl", "go_binary", "go_cross_binary", "go_library")

go_library(
    name = "run_lib",
    srcs = ["main.go"],
    importpath = "github.com/lucasgolven/blazer/cmd/run",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "run",
    embed = [":run_lib"],
    visibility = ["//visibility:public"],
)

go_cross_binary(
    name = "run_linux_amd64",
    target = ":run",
    platform = "@rules_go//go/toolchain:linux_amd64",
    visibility = ["//visibility:public"],
)

go_cross_binary(
    name = "run_linux_arm64",
    target = ":run",
    platform = "@rules_go//go/toolchain:linux_arm64",
    visibility = ["//visibility:public"],
)
